### ISSUE TITLE
changing the src

### ISSUE THREAD

**Issue by jorper98** [mattandersen/vagrant-lamp#14]
Matt - Thank you for this!   
the follwing is not an issue but a question: 
I want to re-route the  src location to my dropbox location... 
I change the share folder in the virtualbox, but that did not do it..  Any ideas as to accomplish this? 
Thanks!

**Comment by mattandersen** [comment]
Assuming that your Dropbox folder is in the regular place and you're on Mac or Linux you need to add the following to the Vagrantfile inside of the `Vagrant.configure` block:

```ruby
config.vm.synced_folder "~/Dropbox", "/vagrant/src"
```

This will mount your Dropbox directory on top of the `src` directory inside of the Virtual Machine. Apache is configured to look point there for files.

**Comment by jorper98** [comment]
Thank you! -- Working perfectly!
