### ISSUE TITLE
Suggestion: add PhpMyAdmin to the build. 

### ISSUE THREAD

**Issue by jorper98** [mattandersen/vagrant-lamp#15]
It would be nice to have phpMyAdmin added automatically to the build... (just an idea!)

**Comment by mattandersen** [comment]
While phpMyAdmin is a useful tool for shared hosting environments. However, when running from your own system you have the freedom to connect directly to the running MySQL server on port 8889. MySQL Workbench and Navicat are great options, to name just two tools.

By all means though, if it is a tool you need, that is the beauty of GitHub. You can fork to make your own customizations, you can merge in any changes from upstream you may want in the future.
