### ISSUE TITLE
Provision.sh aborts when trying to install the php5-pear package.

### ISSUE THREAD

**Issue by marcosandresacevedo** [mattandersen/vagrant-lamp#19]
When the script executes:
apt-get -y install php5 php5-curl php5-mysql php5-sqlite php5-xdebug php5-pear

The following is returned:
E: Unable to locate package php5-pear

This causes cancellation of execution for the provision.sh during automatic provisioning. Modifying it to not install the php5-pear package solves the issue.

If the php5-pear package is not that necessary for the intent of this project,  it might be a good idea to remove it from the script install attempt. Otherwise, another repository might need to be added during the execution of the provision.sh script so that the package can be properly found.

**Comment by kokarn** [comment]
I just ran into the same issue as well so it's absolutly something that's breaking installs.

**Comment by mattandersen** [comment]
Thank you both.
