### ISSUE TITLE
PHP not supported in Apache...

### ISSUE THREAD

**Issue by henrikj242** [mattandersen/vagrant-lamp#20]
Hi,
not sure if I'm just missing something obvious, but PHP is not processed by apache. I just get the plain content of the php files as if they were simply txt files.

**Comment by mattandersen** [comment]
It sounds like provisioning did not succeed. You can re-run the provision step which configures everything like so:

`vagrant provision`

If you still have issues afterwards, post a copy of the output of the above command.

**Comment by henrikj242** [comment]
Still the same after running provision. Here is the output from the command:

`Henriks-MacBook-Pro:vagrant-lamp-PHP55-2016-01-31 hj$ vagrant provision
==> default: Running provisioner: shell...
    default: Running: /var/folders/nc/bnrcl84d6kn9p_kk9tqmyzfw0000gn/T/vagrant-shell20160703-497-a15my6.sh
==> default: stdin: is not a tty
==> default: NOOP
==> default: Ign http://archive.ubuntu.com trusty InRelease
==> default: Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
==> default: Get:2 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
==> default: Hit http://archive.ubuntu.com trusty-backports InRelease
==> default: Hit http://archive.ubuntu.com trusty Release.gpg
==> default: Get:3 http://archive.ubuntu.com trusty-updates/main Sources [277 kB]
==> default: Get:4 http://archive.ubuntu.com trusty-updates/restricted Sources [5,352 B]
==> default: Get:5 http://security.ubuntu.com trusty-security/main Sources [117 kB]
==> default: Get:6 http://archive.ubuntu.com trusty-updates/universe Sources [157 kB]
==> default: Get:7 http://archive.ubuntu.com trusty-updates/multiverse Sources [5,936 B]
==> default: Get:8 http://archive.ubuntu.com trusty-updates/main amd64 Packages [788 kB]
==> default: Get:9 http://security.ubuntu.com trusty-security/universe Sources [38.0 kB]
==> default: Get:10 http://security.ubuntu.com trusty-security/main amd64 Packages [501 kB]
==> default: Get:11 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [15.9 kB]
==> default: Get:12 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [362 kB]
==> default: Get:13 http://security.ubuntu.com trusty-security/universe amd64 Packages [130 kB]
==> default: Get:14 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [13.2 kB]
==> default: Get:15 http://archive.ubuntu.com trusty-updates/main Translation-en [396 kB]
==> default: Get:16 http://security.ubuntu.com trusty-security/main Translation-en [276 kB]
==> default: Get:17 http://archive.ubuntu.com trusty-updates/multiverse Translation-en [7,227 B]
==> default: Get:18 http://archive.ubuntu.com trusty-updates/restricted Translation-en [3,699 B]
==> default: Get:19 http://archive.ubuntu.com trusty-updates/universe Translation-en [190 kB]
==> default: Hit http://archive.ubuntu.com trusty-backports/main Sources
==> default: Hit http://archive.ubuntu.com trusty-backports/restricted Sources
==> default: Hit http://archive.ubuntu.com trusty-backports/universe Sources
==> default: Hit http://archive.ubuntu.com trusty-backports/multiverse Sources
==> default: Get:20 http://security.ubuntu.com trusty-security/universe Translation-en [77.1 kB]
==> default: Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty-backports/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty-backports/multiverse Translation-en
==> default: Hit http://archive.ubuntu.com trusty-backports/restricted Translation-en
==> default: Hit http://archive.ubuntu.com trusty-backports/universe Translation-en
==> default: Hit http://archive.ubuntu.com trusty Release
==> default: Hit http://archive.ubuntu.com trusty/main Sources
==> default: Hit http://archive.ubuntu.com trusty/restricted Sources
==> default: Hit http://archive.ubuntu.com trusty/universe Sources
==> default: Hit http://archive.ubuntu.com trusty/multiverse Sources
==> default: Hit http://archive.ubuntu.com trusty/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty/multiverse Translation-en
==> default: Hit http://archive.ubuntu.com trusty/restricted Translation-en
==> default: Hit http://archive.ubuntu.com trusty/universe Translation-en
==> default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/multiverse Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/restricted Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
==> default: Fetched 3,492 kB in 5s (685 kB/s)
==> default: Reading package lists...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: build-essential is already the newest version.
==> default: binutils-doc is already the newest version.
==> default: git is already the newest version.
==> default: subversion is already the newest version.
==> default: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: apache2 is already the newest version.
==> default: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
==> default: Site 000-default already disabled
==> default: Site vagrant_vhost already enabled
==> default: Module rewrite already enabled
==> default:  * Reloading web server apache2
==> default:  * 
==> default: update-rc.d: warning:  start runlevel arguments (none) do not match apache2 Default-Start values (2 3 4 5)
==> default: update-rc.d: warning:  stop runlevel arguments (none) do not match apache2 Default-Stop values (0 1 6)
==> default:  Enabling system startup links for /etc/init.d/apache2 ...
==> default:  Removing any system startup links for /etc/init.d/apache2 ...
==> default:    /etc/rc0.d/K09apache2
==> default:    /etc/rc1.d/K09apache2
==> default:    /etc/rc2.d/S91apache2
==> default:    /etc/rc3.d/S91apache2
==> default:    /etc/rc4.d/S91apache2
==> default:    /etc/rc5.d/S91apache2
==> default:    /etc/rc6.d/K09apache2
==> default:  Adding system startup for /etc/init.d/apache2 ...
==> default:    /etc/rc0.d/K09apache2 -> ../init.d/apache2
==> default:    /etc/rc1.d/K09apache2 -> ../init.d/apache2
==> default:    /etc/rc6.d/K09apache2 -> ../init.d/apache2
==> default:    /etc/rc2.d/S91apache2 -> ../init.d/apache2
==> default:    /etc/rc3.d/S91apache2 -> ../init.d/apache2
==> default:    /etc/rc4.d/S91apache2 -> ../init.d/apache2
==> default:    /etc/rc5.d/S91apache2 -> ../init.d/apache2
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: mysql-client is already the newest version.
==> default: mysql-server is already the newest version.
==> default: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
==> default: Executing all SQL files in /vagrant/provision-sql folder ...
==> default: -------------------------------------
==> default: EXECUTING /vagrant/provision-sql/01_Example.sql...
==> default: real	0m0.005s
==> default: user	0m0.000s
==> default: sys	0m0.003s
==> default: FINISHED /vagrant/provision-sql/01_Example.sql
==> default: mysql stop/waiting
==> default: mysql start/running, process 1886
==> default: update-rc.d: warning:  start runlevel arguments (none) do not match apache2 Default-Start values (2 3 4 5)
==> default: update-rc.d: warning:  stop runlevel arguments (none) do not match apache2 Default-Stop values (0 1 6)
==> default:  Enabling system startup links for /etc/init.d/apache2 ...
==> default:  Removing any system startup links for /etc/init.d/apache2 ...
==> default:    /etc/rc0.d/K09apache2
==> default:    /etc/rc1.d/K09apache2
==> default:    /etc/rc2.d/S91apache2
==> default:    /etc/rc3.d/S91apache2
==> default:    /etc/rc4.d/S91apache2
==> default:    /etc/rc5.d/S91apache2
==> default:    /etc/rc6.d/K09apache2
==> default:  Adding system startup for /etc/init.d/apache2 ...
==> default:    /etc/rc0.d/K09apache2 -> ../init.d/apache2
==> default:    /etc/rc1.d/K09apache2 -> ../init.d/apache2
==> default:    /etc/rc6.d/K09apache2 -> ../init.d/apache2
==> default:    /etc/rc2.d/S91apache2 -> ../init.d/apache2
==> default:    /etc/rc3.d/S91apache2 -> ../init.d/apache2
==> default:    /etc/rc4.d/S91apache2 -> ../init.d/apache2
==> default:    /etc/rc5.d/S91apache2 -> ../init.d/apache2
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E
==> default: : 
==> default: Unable to locate package php5-pear
==> default: sed: can't read /etc/php5/apache2/php.ini: No such file or directory
==> default: sed: can't read /etc/php5/apache2/php.ini: No such file or directory
==> default: /tmp/vagrant-shell: line 88: /etc/php5/mods-available/xdebug.ini: No such file or directory
==> default:  * Reloading web server apache2
==> default:  * 
==> default: /tmp/vagrant-shell: line 101: php: command not found
==> default: c
==> default: u
==> default: r
==> default: l
==> default: :
==> default:  
==> default: (
==> default: 2
==> default: 3
==> default: )
==> default:  
==> default: F
==> default: a
==> default: iled writing body (0 != 16133)
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by mattandersen** [comment]
The issue you experienced was fixed in the last commit, but I never updated the releases. I'm sorry about that. I have created a new release which should work for you.
