### ISSUE TITLE
disable port

### ISSUE THREAD

**Issue by bencagri** [mattandersen/vagrant-lamp#8]
Hi, thanks for file.

How can i access the box directly http://localhost instead of http://localhost:8888?

Thanks.

**Comment by mattandersen** [comment]
You can alter the Vagrantfile and switch the 8888 to 80. But because any port less than 1023 is a privileged port you have to either run the virtual machine as an administrator or mess with your firewall. It isn't really within the scope of this project.

**Comment by bencagri** [comment]
Thanks for reply @mattandersen
